language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  # Here we list the profiles that we want to test, each one will be tested, per version of PHP, in parallel
  - PROFILE=testing

install:
  # Initialise the database instance for the test
  - mysql -uroot -e 'create database ca_test;'
  - mysql -uroot -e "grant all on ca_test.* to 'ca_test'@'localhost' identified by 'password';"
  # Set environment variables
  - export COLLECTIVEACCESS_HOME="$(pwd)"
  - export PATH="$PATH:$COLLECTIVEACCESS_HOME/support/bin"
  # Create setup.php
  - ln -s .travis.setup.php setup.php
  # Install the testing profile
  - support/bin/caUtils install --hostname=localhost --setup="$(pwd)/tests/setup-tests.php" --skip-roles --profile-name=$PROFILE --admin-email=support@collectiveaccess.org > install.log

before_script:
  # Go into the tests directory to run the tests
  - cd tests/

branches:
  only:
    - develop
    - master
    - master-fix
    - dev/configSync
